/**
 * @file      hal_warmstart.c
 *
 * @brief     BSP Warmstart hook implementation for FPB-RA0E2
 *
 *            This function is called at various points during the startup process.
 *            It initializes the IOPORT driver with the configuration generated by e2studio.
 * 
 * The Clear BSD License
 * Copyright Semtech Corporation 2025. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the disclaimer
 * below) provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Semtech corporation nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
 * THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * -----------------------------------------------------------------------------
 * --- DEPENDENCIES ------------------------------------------------------------
 */

#include "hal_data.h"
#include "common_data.h"

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC FUNCTIONS DEFINITION ---------------------------------------------
 */

/**
 * @brief BSP Warm Start callback
 *
 * This function is called at various points during the startup process.
 * We use the BSP_WARM_START_POST_C event (after C runtime initialization)
 * to configure pins using the FSP IOPORT driver.
 *
 * @param[in]  event  Where in the startup process the code currently is
 */
void R_BSP_WarmStart( bsp_warm_start_event_t event )
{
    if( BSP_WARM_START_RESET == event )
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0
        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery.
         * Placing the enable here, before clock and C runtime initialization,
         * should negate the need for a delay since initialization typically takes > 6us. */
#endif
    }

    if( BSP_WARM_START_POST_C == event )
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins using FSP IOPORT driver with generated configuration */
        R_IOPORT_Open( &IOPORT_CFG_CTRL, &IOPORT_CFG_NAME );
    }
}

/* --- EOF ------------------------------------------------------------------ */
